name: .NET Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Tyrian-Zero.sln
      Project_Name: Tyrian-Zero.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

      - name: Execute unit tests
        run: dotnet test ${{ env.Solution_Name }} --no-restore --verbosity normal

      - name: Publish
        if: matrix.configuration == 'Release'
        run: dotnet publish ${{ env.Project_Name }} -c ${{ matrix.configuration }} -o publish --no-restore

      - name: Upload artifact
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: Tyrian-Zero
          path: publish
